# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_campo', models.CharField(max_length=30)),
                ('tipo_de_valor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_dispositivo', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=40)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('esta_habilitado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_proyecto', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_sensor', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('esta_habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('fecha_hora_lectura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
