# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20170819_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='latitud',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='longitud',
            field=models.FloatField(blank=True),
        ),
    ]
