# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170927_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
