# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171019_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='valor',
            name='id_paquete',
            field=models.IntegerField(default=0),
        ),
    ]
